/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/album/[id]': RouteRecordInfo<'/album/[id]', '/album/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/artist/[id]': RouteRecordInfo<'/artist/[id]', '/artist/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/Favoris': RouteRecordInfo<'/Favoris', '/Favoris', Record<never, never>, Record<never, never>>,
    '/Recherche': RouteRecordInfo<'/Recherche', '/Recherche', Record<never, never>, Record<never, never>>,
    '/song/[id]': RouteRecordInfo<'/song/[id]', '/song/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
